package edu.kit.aifb.gwifi.util.nlp;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Language {

	public static Language UNKNOWN = new Language("unknown");

	public static Language EN = new Language("en", "eng", "englisch", "english");
	public static Language DE = new Language("de", "ger", "deu", "deutsch", "german");
	public static Language ES = new Language("es", "spa", "spanisch", "spanish");
	public static Language ZH = new Language("zh", "chi", "chinese", "chinesisch");
	public static Language CA = new Language("ca", "cat", "katalanisch", "catalan");
	public static Language SL = new Language("sl", "slv", "slowenisch", "slovenian", "slovene");
	public static Language FR = new Language("fr", "fre", "franzoesisch", "french");
	public static Language IT = new Language("it", "ita", "italienisch", "italian");
	public static Language PT = new Language("pt", "por", "portugiesisch", "portuguese");
	public static Language SR = new Language("sr", "srp", "serbisch", "serbian");
	public static Language RU = new Language("ru", "rus", "russisch", "russian");
	public static Language EU = new Language("eu", "eus", "baskisch", "basque");
	public static Language HR = new Language("hr", "hrv", "kroatische", "croatian");
	
	public static Language FI = new Language("fi", "fin", "finnisch", "finnish");
	public static Language DK = new Language("dk", "dan", "daenisch", "danish");
	public static Language EE = new Language("ee", "est", "estnisch", "estonian");
	public static Language JP = new Language("jp", "jpn", "japanisch", "japanese");
	public static Language KR = new Language("kr", "kor", "koreanisch", "korean");
	public static Language NL = new Language("nl", "dut", "niederl�ndisch", "dutch");
	public static Language NO = new Language("no", "nor", "norwegisch", "norwegian");
	public static Language SE = new Language("se", "swe", "schwedisch", "swedish");
	public static Language SORB = new Language("sorb", "wen", "sorbisch", "sorbian");
	public static Language TR = new Language("tr", "tur", "tuerkisch", "turkish");
	public static Language ABK = new Language("abk", "abchasisch");
	public static Language ACE = new Language("ace", "aceh-sprache");
	public static Language ACH = new Language("ach", "acholi-sprache");
	public static Language ADA = new Language("ada", "adangme-sprache");
	public static Language ADY = new Language("ady", "adygisch");
	public static Language AFH = new Language("afh", "afrihili");
	public static Language AFR = new Language("afr", "afrikaans");
	public static Language EGY = new Language("egy", "�gyptisch");
	public static Language AIN = new Language("ain", "ainu-sprache");
	public static Language AKA = new Language("aka", "akan-sprache");
	public static Language AKK = new Language("akk", "akkadisch");
	public static Language ALB = new Language("alb", "albanisch");
	public static Language ALE = new Language("ale", "aleutisch");
	public static Language ALG = new Language("alg", "algonkin-sprachen (andere)");
	public static Language GEZ = new Language("gez", "alt�thiopisch");
	public static Language TUT = new Language("tut", "altaische sprachen (andere)");
	public static Language ANG = new Language("ang", "altenglisch");
	public static Language FRO = new Language("fro", "altfranz�sisch");
	public static Language GOH = new Language("goh", "althochdeutsch");
	public static Language SGA = new Language("sga", "altirisch");
	public static Language NWC = new Language("nwc", "alt-newari");
	public static Language NON = new Language("non", "altnorwegisch");
	public static Language PRO = new Language("pro", "altokzitanisch");
	public static Language PEO = new Language("peo", "altpersisch");
	public static Language AMH = new Language("amh", "amharisch");
	public static Language ANP = new Language("anp", "anga-sprache");
	public static Language APA = new Language("apa", "apachen-sprache");
	public static Language ARA = new Language("ara", "arabisch");
	public static Language ARG = new Language("arg", "aragonesisch");
	public static Language ARC = new Language("arc", "aram�isch");
	public static Language ARP = new Language("arp", "arapaho-sprache");
	public static Language ARN = new Language("arn", "arauka-sprachen");
	public static Language ARW = new Language("arw", "arawak-sprachen");
	public static Language ARM = new Language("arm", "armenisch");
	public static Language AZE = new Language("aze", "aserbeidschanisch");
	public static Language ASM = new Language("asm", "assamesisch");
	public static Language AST = new Language("ast", "asturisch");
	public static Language ATH = new Language("ath", "athapaskische sprachen");
	public static Language AUS = new Language("aus", "australische sprachen");
	public static Language MAP = new Language("map", "austronesische sprachen (andere)");
	public static Language AVE = new Language("ave", "avestisch");
	public static Language AWA = new Language("awa", "awadhi");
	public static Language AVA = new Language("ava", "awarisch");
	public static Language AYM = new Language("aym", "aymar�-sprache");
	public static Language IND = new Language("ind", "bahasa");
	public static Language BAN = new Language("ban", "balinesisch");
	public static Language BAT = new Language("bat", "baltische sprachen (andere)");
	public static Language BAM = new Language("bam", "bambara-sprache");
	public static Language BAI = new Language("bai", "bamileke-sprache");
	public static Language BAD = new Language("bad", "banda-sprache");
	public static Language BNT = new Language("bnt", "bantusprachen (andere)");
	public static Language BAS = new Language("bas", "basaa-sprache");
	public static Language BAK = new Language("bak", "baschkirisch");
	public static Language BAQ = new Language("baq", "baskisch");
	public static Language BTK = new Language("btk", "batak-sprache");
	public static Language BIS = new Language("bis", "beach-la-mar");
	public static Language BEJ = new Language("bej", "bedauye");
	public static Language BAL = new Language("bal", "belutschisch");
	public static Language BEM = new Language("bem", "bemba-sprache");
	public static Language BEN = new Language("ben", "bengali");
	public static Language BER = new Language("ber", "berbersprachen (andere)");
	public static Language BHO = new Language("bho", "bhojpuri");
	public static Language BZO = new Language("bzo", "bhutanisch");
	public static Language BIK = new Language("bik", "bikol-sprache");
	public static Language BIH = new Language("bih", "bihari");
	public static Language BYN = new Language("byn", "bilin-sprache");
	public static Language BUR = new Language("bur", "birmanisch");
	public static Language BLA = new Language("bla", "blackfoot-sprache");
	public static Language NOB = new Language("nob", "bokm�l");
	public static Language BOS = new Language("bos", "bosnisch");
	public static Language BRA = new Language("bra", "braj-bhakha");
	public static Language BRE = new Language("bre", "bretonisch");
	public static Language BUG = new Language("bug", "bugi-sprache");
	public static Language BUL = new Language("bul", "bulgarisch");
	public static Language BUA = new Language("bua", "burjatisch");
	public static Language CAD = new Language("cad", "caddo-sprachen");
	public static Language CEB = new Language("ceb", "cebuano");
	public static Language CMC = new Language("cmc", "cham-sprachen");
	public static Language CHA = new Language("cha", "chamorro-sprache");
	public static Language CHR = new Language("chr", "cherokee-sprache");
	public static Language CHY = new Language("chy", "cheyenne-sprache");
	public static Language CHB = new Language("chb", "chibcha-sprachen");
	public static Language CHN = new Language("chn", "chinook-jargon");
	public static Language CHP = new Language("chp", "chipewyan-sprache");
	public static Language CHO = new Language("cho", "choctaw-sprache");
	public static Language CRE = new Language("cre", "cree-sprache");
	public static Language DAY = new Language("day", "dajakisch");
	public static Language DAK = new Language("dak", "dakota-sprache");
	public static Language DAR = new Language("dar", "darginisch");
	public static Language DEL = new Language("del", "delaware-sprache");
	public static Language DIN = new Language("din", "dinka-sprache");
	public static Language DOI = new Language("doi", "dogri");
	public static Language DGR = new Language("dgr", "dogrib-sprache");
	public static Language DRA = new Language("dra", "drawidische sprachen (andere)");
	public static Language DUA = new Language("dua", "duala-sprachen");
	public static Language DYU = new Language("dyu", "dyula-sprache");
	public static Language DZO = new Language("dzo", "dzongkha");
	public static Language BIN = new Language("bin", "edo-sprache");
	public static Language EFI = new Language("efi", "efik");
	public static Language EKA = new Language("eka", "ekajuk");
	public static Language ELX = new Language("elx", "elamisch");
	public static Language TVL = new Language("tvl", "elliceanisch");
	public static Language MYV = new Language("myv", "erza-mordwinisch");
	public static Language ESK = new Language("esk", "eskimo-aleutischen sprache");
	public static Language EPO = new Language("epo", "esperanto");
	public static Language EWE = new Language("ewe", "ewe-sprache");
	public static Language EWO = new Language("ewo", "ewondo");
	public static Language FAO = new Language("fao", "f�r�isch");
	public static Language FAT = new Language("fat", "fante-sprache");
	public static Language FIJ = new Language("fij", "fidschi-sprache");
	public static Language FIU = new Language("fiu", "finnougrische sprachen (andere)");
	public static Language FON = new Language("fon", "fon-sprache");
	public static Language FRY = new Language("fry", "friesisch");
	public static Language FUR = new Language("fur", "friulisch");
	public static Language FUL = new Language("ful", "ful");
	public static Language GAA = new Language("gaa", "ga-sprache");
	public static Language GLA = new Language("gla", "g�lisch-schottisch");
	public static Language GLG = new Language("glg", "galicisch");
	public static Language GAG = new Language("gag", "galicisch");
	public static Language ORM = new Language("orm", "galla-sprache");
	public static Language LUG = new Language("lug", "ganda-sprache");
	public static Language GAY = new Language("gay", "gayo-sprache");
	public static Language GBA = new Language("gba", "gbaya-sprache");
	public static Language GEO = new Language("geo", "georgisch");
	public static Language GEM = new Language("gem", "germanische sprachen (andere)");
	public static Language GIL = new Language("gil", "gilbertesisch");
	public static Language GON = new Language("gon", "gondi-sprache");
	public static Language GOR = new Language("gor", "gorontalesisch");
	public static Language GOT = new Language("got", "gotisch");
	public static Language GRB = new Language("grb", "grebo-sprache");
	public static Language GRC = new Language("grc", "griechisch");
	public static Language KAL = new Language("kal", "gr�nl�ndisch");
	public static Language GRN = new Language("grn", "guaran�-sprache");
	public static Language GUJ = new Language("guj", "gujariti-sprache");
	public static Language HAI = new Language("hai", "haida-sprache");
	public static Language HAT = new Language("hat", "ha�tien");
	public static Language AFA = new Language("afa", "hamitosemitische sprachen (andere)");
	public static Language HAU = new Language("hau", "haussa-sprache");
	public static Language HAW = new Language("haw", "hawaiisch");
	public static Language HEB = new Language("heb", "hebr�isch");
	public static Language HER = new Language("her", "herero-sprache");
	public static Language HIT = new Language("hit", "hethitisch");
	public static Language HIL = new Language("hil", "hiligaynon-sprache");
	public static Language HIM = new Language("him", "himachali");
	public static Language HIN = new Language("hin", "hindi");
	public static Language HMO = new Language("hmo", "hiri-motu");
	public static Language HUP = new Language("hup", "hupa-sprache");
	public static Language IBA = new Language("iba", "iban-sprache");
	public static Language IBO = new Language("ibo", "ibo-sprache");
	public static Language IDO = new Language("ido", "ido");
	public static Language IJO = new Language("ijo", "ijo-sprache");
	public static Language ILO = new Language("ilo", "ilokano-sprache");
	public static Language SMN = new Language("smn", "inarisaamisch");
	public static Language NAI = new Language("nai", "indianersprachen, nordamerika (andere)");
	public static Language SAI = new Language("sai", "indianersprachen, s�damerika (andere)");
	public static Language CAI = new Language("cai", "indianersprachen, zentralamerika (andere)");
	public static Language INC = new Language("inc", "indoarische sprachen (andere)");
	public static Language INE = new Language("ine", "indogermanische sprachen (andere)");
	public static Language INH = new Language("inh", "inguschisch");
	public static Language INA = new Language("ina", "interlingua");
	public static Language ILE = new Language("ile", "interlingue");
	public static Language IKU = new Language("iku", "inuktitut");
	public static Language IPK = new Language("ipk", "inupik");
	public static Language IRA = new Language("ira", "iranische sprachen (andere)");
	public static Language GLE = new Language("gle", "irisch");
	public static Language IRO = new Language("iro", "irokesische sprachen");
	public static Language ICE = new Language("ice", "isl�ndisch");
	public static Language SAH = new Language("sah", "jakutisch");
	public static Language JAV = new Language("jav", "javanisch");
	public static Language YID = new Language("yid", "jiddisch");
	public static Language LAD = new Language("lad", "judenspanisch");
	public static Language JRB = new Language("jrb", "j�disch-arabisch");
	public static Language JPR = new Language("jpr", "j�disch-persisch");
	public static Language KBD = new Language("kbd", "kabardinisch");
	public static Language KAB = new Language("kab", "kabylisch");
	public static Language KAC = new Language("kac", "kachin-sprache");
	public static Language XAL = new Language("xal", "kalm�ckisch");
	public static Language KAM = new Language("kam", "kamba-sprache");
	public static Language KHM = new Language("khm", "kambodschanisch");
	public static Language KAN = new Language("kan", "kannada");
	public static Language KAU = new Language("kau", "kanuri-sprache");
	public static Language KAA = new Language("kaa", "karakalpakisch");
	public static Language KRC = new Language("krc", "karatschaiisch-balkarisch");
	public static Language KRL = new Language("krl", "karelisch");
	public static Language KAR = new Language("kar", "karenisch");
	public static Language CAR = new Language("car", "karibische sprachen");
	public static Language KAZ = new Language("kaz", "kasachisch");
	public static Language KAS = new Language("kas", "kaschmiri");
	public static Language CSB = new Language("csb", "kaschubisch");
	public static Language CAU = new Language("cau", "kaukasische");
	public static Language KAW = new Language("kaw", "kawi");
	public static Language KHA = new Language("kha", "khasi-sprache");
	public static Language KHI = new Language("khi", "khoisan-sprachen (andere)");
	public static Language CEL = new Language("cel", "keltische sprachen (andere)");
	public static Language MAG = new Language("mag", "khotta");
	public static Language KIK = new Language("kik", "kikuyu-sprache");
	public static Language KMB = new Language("kmb", "kimbundu-sprache");
	public static Language KIR = new Language("kir", "kirgisisch");
	public static Language CHU = new Language("chu", "kirchenslawisch");
	public static Language TLH = new Language("tlh", "klingonisch");
	public static Language KOM = new Language("kom", "komi-sprache");
	public static Language KON = new Language("kon", "kongo-sprache");
	public static Language KOK = new Language("kok", "konkani");
	public static Language COP = new Language("cop", "koptisch");
	public static Language COR = new Language("cor", "kornisch");
	public static Language COS = new Language("cos", "korsisch");
	public static Language KOS = new Language("kos", "kosreanisch");
	public static Language KPE = new Language("kpe", "kpelle-sprache");
	public static Language CPE = new Language("cpe", "kreolisch-englisch (andere)");
	public static Language CPF = new Language("cpf", "kreolisch-franz�sisch (andere)");
	public static Language CPP = new Language("cpp", "kreolisch-portugiesisch (andere)");
	public static Language CRP = new Language("crp", "kreolische sprachen; pidginsprachen (andere)");
	public static Language CRH = new Language("crh", "krimtatarisch");
	public static Language SCR = new Language("scr", "kroatisch");
	public static Language KRO = new Language("kro", "kru-sprachen");
	public static Language KUM = new Language("kum", "kum�kisch");
	public static Language ART = new Language("art", "kunstsprachen (andere)");
	public static Language KUR = new Language("kur", "kurdisch");
	public static Language CUS = new Language("cus", "kuschitische sprachen (andere)");
	public static Language GWI = new Language("gwi", "kutchin-sprache");
	public static Language KUT = new Language("kut", "kutenai-sprache");
	public static Language KUA = new Language("kua", "kwanyama-sprache");
	public static Language WEL = new Language("wel", "kymrisch / walisisch");
	public static Language LAH = new Language("lah", "lahndi");
	public static Language III = new Language("iii", "lalo-sprache");
	public static Language LAM = new Language("lam", "lamba-sprache <bantusprache>");
	public static Language LAO = new Language("lao", "laotisch");
	public static Language LAT = new Language("lat", "latein");
	public static Language LEZ = new Language("lez", "lesgisch");
	public static Language LAV = new Language("lav", "lettisch");
	public static Language LIM = new Language("lim", "limburgisch");
	public static Language LIN = new Language("lin", "lingala");
	public static Language LIT = new Language("lit", "litauisch");
	public static Language JBO = new Language("jbo", "lojban");
	public static Language LUB = new Language("lub", "luba-katanga-sprache");
	public static Language LUI = new Language("lui", "luise�o-sprache");
	public static Language SMJ = new Language("smj", "lulesaamisch");
	public static Language LUA = new Language("lua", "lulua-sprache");
	public static Language LUN = new Language("lun", "lunda-sprache");
	public static Language LUO = new Language("luo", "luo-sprache");
	public static Language LUS = new Language("lus", "lushai-sprache");
	public static Language LTZ = new Language("ltz", "luxemburgisch");
	public static Language MAD = new Language("mad", "maduresisch");
	public static Language MAI = new Language("mai", "maithili");
	public static Language MAK = new Language("mak", "makassarisch");
	public static Language MAC = new Language("mac", "makedonisch");
	public static Language MLG = new Language("mlg", "malagassi-sprache");
	public static Language MAY = new Language("may", "malaiisch");
	public static Language MAL = new Language("mal", "malayalam");
	public static Language DIV = new Language("div", "maledivisch");
	public static Language MAN = new Language("man", "malinke-sprache");
	public static Language MLT = new Language("mlt", "maltesisch");
	public static Language MDR = new Language("mdr", "mandaresisch");
	public static Language MNC = new Language("mnc", "mandschurisch");
	public static Language MNO = new Language("mno", "manobo-sprache");
	public static Language GLV = new Language("glv", "manx");
	public static Language MAO = new Language("mao", "maori-sprache");
	public static Language MAR = new Language("mar", "marathi");
	public static Language MAH = new Language("mah", "marschallesisch");
	public static Language MWR = new Language("mwr", "mirwiri");
	public static Language MAS = new Language("mas", "massai-sprache");
	public static Language MYN = new Language("myn", "maya-sprachen");
	public static Language UMB = new Language("umb", "mbundu-sprache");
	public static Language MNI = new Language("mni", "meithei-sprache");
	public static Language MEN = new Language("men", "mende-sprache");
	public static Language HMN = new Language("hmn", "miao-sprachen");
	public static Language MIC = new Language("mic", "micmac-sprache");
	public static Language MIN = new Language("min", "minangkabau-sprache");
	public static Language MWL = new Language("mwl", "mirandesisch");
	public static Language ENM = new Language("enm", "mittelenglisch");
	public static Language FRM = new Language("frm", "mittelfranz�sisch");
	public static Language GMH = new Language("gmh", "mittelhochdeutsch");
	public static Language MGA = new Language("mga", "mittelirisch");
	public static Language DUM = new Language("dum", "mittelniederl�ndisch");
	public static Language PAL = new Language("pal", "mittelpersisch");
	public static Language MOH = new Language("moh", "mohawk-sprache");
	public static Language MDF = new Language("mdf", "mokscha-sprache");
	public static Language MOL = new Language("mol", "moldauisch");
	public static Language MKH = new Language("mkh", "mon-khmer-sprachen (andere)");
	public static Language LOL = new Language("lol", "mongo-sprache");
	public static Language MON = new Language("mon", "mongolisch");
	public static Language MOS = new Language("mos", "mossi-sprache");
	public static Language MUN = new Language("mun", "mundasprachen (andere)");
	public static Language MUS = new Language("mus", "muskogisch");
	public static Language NAH = new Language("nah", "nahuatl");
	public static Language NAU = new Language("nau", "nauruanisch");
	public static Language NAV = new Language("nav", "navajo-sprache");
	public static Language NDE = new Language("nde", "ndebele-sprache <simbabwe>");
	public static Language NBL = new Language("nbl", "ndebele-sprache<transvaal>");
	public static Language NDO = new Language("ndo", "ndonga");
	public static Language NAP = new Language("nap", "neapel / mundart");
	public static Language NEP = new Language("nep", "nepali");
	public static Language GRE = new Language("gre", "neugriechisch");
	public static Language TPI = new Language("tpi", "neumelanesisch");
	public static Language NEW = new Language("new", "newiri");
	public static Language NIA = new Language("nia", "nias-sprache");
	public static Language NDS = new Language("nds", "niederdeutsch");
	public static Language DSB = new Language("dsb", "niedersorbisch");
	public static Language NIC = new Language("nic", "nigerkordofanische sprachen (andere)");
	public static Language SSA = new Language("ssa", "nilosaharanische sprachen (andere)");
	public static Language NIU = new Language("niu", "niue-sprache");
	public static Language NYN = new Language("nyn", "nkole-sprache");
	public static Language NOG = new Language("nog", "nogaisch");
	public static Language FRR = new Language("frr", "nordfriesisch");
	public static Language SME = new Language("sme", "nordsaamisch");
	public static Language NUB = new Language("nub", "nubische sprachen");
	public static Language NYM = new Language("nym", "nyamwezi-sprache");
	public static Language NYA = new Language("nya", "nyanja-sprache");
	public static Language NNO = new Language("nno", "nynorsk");
	public static Language NYO = new Language("nyo", "nyoro-sprache");
	public static Language NZI = new Language("nzi", "nzima-sprache");
	public static Language HSB = new Language("hsb", "obersorbisch");
	public static Language OJI = new Language("oji", "ojibwa-sprache");
	public static Language OCI = new Language("oci", "okzitanisch");
	public static Language KRU = new Language("kru", "oraon-sprache");
	public static Language ORI = new Language("ori", "oriya-sprache");
	public static Language OSA = new Language("osa", "osage-sprache");
	public static Language OTA = new Language("ota", "osmanisch");
	public static Language OSS = new Language("oss", "ossetisch");
	public static Language FRS = new Language("frs", "ostfriesisch");
	public static Language RAP = new Language("rap", "osterinsel-sprache");
	public static Language OTO = new Language("oto", "otomangue-sprachen");
	public static Language PAU = new Language("pau", "palau-sprache");
	public static Language PLI = new Language("pli", "pili");
	public static Language PAM = new Language("pam", "pampanggan-sprache");
	public static Language PAN = new Language("pan", "pandschabi-sprache");
	public static Language PAG = new Language("pag", "pangasinan-sprache");
	public static Language FAN = new Language("fan", "pangwe-sprache");
	public static Language PAP = new Language("pap", "papiamento");
	public static Language PAA = new Language("paa", "papuasprachen (andere)");
	public static Language PUS = new Language("pus", "paschtu");
	public static Language NSO = new Language("nso", "pedi-sprache");
	public static Language PER = new Language("per", "persisch");
	public static Language PHI = new Language("phi", "philippinen-austronesisch (andere)");
	public static Language PHN = new Language("phn", "ph�nikisch");
	public static Language FIL = new Language("fil", "pilipino");
	public static Language POL = new Language("pol", "polnisch");
	public static Language PON = new Language("pon", "ponapeanisch");
	public static Language PRA = new Language("pra", "prikrit");
	public static Language QUE = new Language("que", "quechua-sprache");
	public static Language ROH = new Language("roh", "r�toromanisch");
	public static Language RAJ = new Language("raj", "rijasthini");
	public static Language RAR = new Language("rar", "rarotonganisch");
	public static Language ROM = new Language("rom", "romani");
	public static Language ROA = new Language("roa", "romanische sprache");
	public static Language LOZ = new Language("loz", "rotse-sprache");
	public static Language RUM = new Language("rum", "rum�nisch");
	public static Language RUN = new Language("run", "rundi-sprache");
	public static Language RUS = new Language("rus", "russisch");
	public static Language KIN = new Language("kin", "rwanda-sprache");
	public static Language SMI = new Language("smi", "saamisch (andere)");
	public static Language KHO = new Language("kho", "sakisch");
	public static Language SAL = new Language("sal", "salish-sprache");
	public static Language SAM = new Language("sam", "samaritanisch");
	public static Language SMO = new Language("smo", "samoanisch");
	public static Language SAD = new Language("sad", "sandawe-sprache");
	public static Language SAG = new Language("sag", "sango-sprache");
	public static Language SAN = new Language("san", "sanskrit");
	public static Language SAT = new Language("sat", "santili");
	public static Language SRD = new Language("srd", "sardisch");
	public static Language SAS = new Language("sas", "sasak");
	public static Language SHN = new Language("shn", "schan-sprache");
	public static Language SNA = new Language("sna", "schona-sprache");
	public static Language SCO = new Language("sco", "schottisch");
	public static Language GSW = new Language("gsw", "schweizerdeutsch");
	public static Language SEL = new Language("sel", "selkupisch");
	public static Language SEM = new Language("sem", "semitische sprachen (andere)");
	public static Language SCC = new Language("scc", "serbisch");
	public static Language SRR = new Language("srr", "serer-sprache");
	public static Language SHO = new Language("sho", "shona <simbabwe>");
	public static Language SID = new Language("sid", "sidamo-sprache");
	public static Language SND = new Language("snd", "sindhi-sprache");
	public static Language SIN = new Language("sin", "singhalesisch");
	public static Language SIT = new Language("sit", "sinotibetische sprachen (andere)");
	public static Language SIO = new Language("sio", "sioux-sprachen");
	public static Language SCN = new Language("scn", "sizilianisch");
	public static Language SMS = new Language("sms", "skoltsaamisch");
	public static Language DEN = new Language("den", "slave-sprache");
	public static Language SLA = new Language("sla", "slawische sprachen (andere)");
	public static Language SLO = new Language("slo", "slowakisch");
	public static Language SOG = new Language("sog", "sogdisch");
	public static Language SOM = new Language("som", "somali");
	public static Language SON = new Language("son", "songhai-sprache");
	public static Language SNK = new Language("snk", "soninke-sprache");
	public static Language SRN = new Language("srn", "sranantongo");
	public static Language SOT = new Language("sot", "s�d-sotho-sprache");
	public static Language ALT = new Language("alt", "s�daltaisch");
	public static Language SMA = new Language("sma", "s�dsaamisch");
	public static Language SUK = new Language("suk", "sukuma-sprache");
	public static Language SUX = new Language("sux", "sumerisch");
	public static Language SUN = new Language("sun", "sundanesisch");
	public static Language SUS = new Language("sus", "susu");
	public static Language SWA = new Language("swa", "swahili");
	public static Language SSW = new Language("ssw", "swasi-sprache");
	public static Language SYR = new Language("syr", "syrisch");
	public static Language TGK = new Language("tgk", "tadschikisch");
	public static Language TGL = new Language("tgl", "tagalog");
	public static Language TAH = new Language("tah", "tahitisch");
	public static Language TMH = new Language("tmh", "tamaseq");
	public static Language TAM = new Language("tam", "tamil");
	public static Language TAT = new Language("tat", "tatarisch");
	public static Language TEL = new Language("tel", "telugu-sprache");
	public static Language TEM = new Language("tem", "temne-sprache");
	public static Language TER = new Language("ter", "tereno-sprache");
	public static Language TET = new Language("tet", "tetum-sprache");
	public static Language THA = new Language("tha", "thail�ndisch");
	public static Language TAI = new Language("tai", "thaisprachen (andere)");
	public static Language TIB = new Language("tib", "tibetisch");
	public static Language TIG = new Language("tig", "tigre-sprache");
	public static Language TIR = new Language("tir", "tigrinja-sprache");
	public static Language TIV = new Language("tiv", "tiv-sprache");
	public static Language TLI = new Language("tli", "tlingit-sprache");
	public static Language TKL = new Language("tkl", "tokelauanisch");
	public static Language TOG = new Language("tog", "tonga <bantusprache, sambia>");
	public static Language TON = new Language("ton", "tongaisch");
	public static Language CHK = new Language("chk", "trukesisch");
	public static Language CHG = new Language("chg", "tschagataisch");
	public static Language CZE = new Language("cze", "tschechisch");
	public static Language CHM = new Language("chm", "tscheremissisch");
	public static Language CHE = new Language("che", "tschetschenisch");
	public static Language CHV = new Language("chv", "tschuwaschisch");
	public static Language TSI = new Language("tsi", "tsimshian-sprache");
	public static Language TSO = new Language("tso", "tsonga-sprache");
	public static Language TSN = new Language("tsn", "tswana-sprache");
	public static Language TUM = new Language("tum", "tumbuka-sprache");
	public static Language TUP = new Language("tup", "tupi-sprache");
	public static Language TUK = new Language("tuk", "turkmenisch");
	public static Language TYV = new Language("tyv", "tuwinisch");
	public static Language TWI = new Language("twi", "twi-sprache");
	public static Language UDM = new Language("udm", "udmurtisch");
	public static Language UGA = new Language("uga", "ugaritisch");
	public static Language UIG = new Language("uig", "uigurisch");
	public static Language UKR = new Language("ukr", "ukrainisch");
	public static Language HUN = new Language("hun", "ungarisch");
	public static Language URD = new Language("urd", "urdu");
	public static Language UZB = new Language("uzb", "usbekisch");
	public static Language VAI = new Language("vai", "vai-sprache");
	public static Language VEN = new Language("ven", "venda-sprache");
	public static Language VIE = new Language("vie", "vietnamesisch");
	public static Language VOL = new Language("vol", "volap�k");
	public static Language WAK = new Language("wak", "wakash-sprachen");
	public static Language WAL = new Language("wal", "walamo-sprache");
	public static Language WLN = new Language("wln", "wallonisch");
	public static Language WAR = new Language("war", "waray");
	public static Language WAS = new Language("was", "washo-sprache");
	public static Language BEL = new Language("bel", "wei�russisch");
	public static Language WOL = new Language("wol", "wolof-sprache");
	public static Language VOT = new Language("vot", "wotisch");
	public static Language XHO = new Language("xho", "xhosa-sprache");
	public static Language YAO = new Language("yao", "yao-sprache <bantusprache>");
	public static Language YAP = new Language("yap", "yapesisch");
	public static Language YOR = new Language("yor", "yoruba-sprache");
	public static Language YPK = new Language("ypk", "yupik-sprache");
	public static Language ZND = new Language("znd", "zande-sprachen");
	public static Language ZAP = new Language("zap", "zapotekisch");
	public static Language ZZA = new Language("zza", "zazaki");
	public static Language SGN = new Language("sgn", "zeichensprachen");
	public static Language ZEN = new Language("zen", "zenaga");
	public static Language ZHA = new Language("zha", "zhuang");
	public static Language ZUL = new Language("zul", "zulu-sprache");
	public static Language ZUN = new Language("zun", "zu�i-sprache");

	private static Map<String, Language> s_labelToLanguage;
	private static Map<Language, List<String>> s_languageToLabels;
	private static Map<Language, String> s_languageToLabel;

	private Language(String... labels) {

		// s_labelToLanguage initialisieren
		if (s_labelToLanguage == null) {
			s_labelToLanguage = new HashMap<String, Language>();
		}
		for (String label : labels) {
			s_labelToLanguage.put(label, this);
		}
		
		if (s_languageToLabels == null) {
			s_languageToLabels = new HashMap<Language, List<String>>();
		}
		List<String> list = new ArrayList<String>();
		s_languageToLabels.put(this, list);
		for (String label : labels) {
			list.add(label);
		}

		// s_languageToLabel initialisieren
		if (s_languageToLabel == null) {
			s_languageToLabel = new HashMap<Language, String>();
		}
		if (labels.length > 0) {
			s_languageToLabel.put(this, labels[0]);
		}

	}

	public static Language getLanguage(String label) {
		return s_labelToLanguage.get(label);
	}

	public static String getLabel(Language lang) {
		return s_languageToLabel.get(lang);
	}
	
	public static List<String> getLabels(Language lang) {
		return s_languageToLabels.get(lang);
	}

	public static List<Language> getLanguages(String[] labels) {
		List<Language> languages = new ArrayList<Language>();
		for (String label : labels) {
			Language l = getLanguage(label);
			if (l != null) {
				languages.add(l);
			}
		}
		return languages;
	}

	public static Collection<Language> getSupportedLanguages() {
		return s_languageToLabel.keySet();
	}

	public String getLabel() {
		return s_languageToLabel.get(this);
	}
	
	public String toString() {
		return s_languageToLabel.get(this);
	}
}
